### ISSUE TITLE
Name Error

### ISSUE THREAD

**Issue by Zumbalamambo** [Ryaninthegame/3D-Face-Recognition-Similarity-in-medical.#1]
Please share the loss function. It throws the following error,

`NameError: name 'NTXentLoss' is not defined
`

**Comment by Ryaninthegame** [comment]
I fixed if. Please check again.
By the way, my project dataset is contour map of face in med.
I dont't think to use Resnet-50 to extract features, so I adjust slightly
SimCLR model, not original SimCLR model.

Zumbalamambo <notifications@github.com> 於 2021年2月24日 週三 上午2:54寫道：

**Comment by Zumbalamambo** [comment]
thank you!
